feat: add silentLogin
casdoor/casdoor-python-vue-sdk-example pull request #10
Opened 2023-03-18 05:47 UTC by jakiuncle

feat: add silentLogin

2023-03-18 05:51 UTC, jakiuncle commented
https://user-images.githubusercontent.com/88994283/226087790-bc869aa4-8f1f-4e37-aa79-da8f360b6a88.mp4

2023-03-18 06:46 UTC, hsluoyz requested changes

2023-03-18 06:46 UTC, hsluoyz commented on web/package.json
>    "dependencies": {
demo video?

2023-03-18 06:46 UTC, hsluoyz commented on web/yarn.lock
> +  resolved "https://registry.yarnpkg.com/casdoor-js-sdk/-/casdoor-js-sdk-0.8.0.tgz#ce32c49fdfe7f24a8139d676a341ad7e78c50f38"
Use `registry.yarnpkg.com` everywhere

2023-03-19 10:38 UTC, hsluoyz approved these changes

2023-03-19 10:38 UTC, merged